/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/demos': RouteRecordInfo<
      '/demos',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/change-mysql-password': RouteRecordInfo<
      '/posts/change-mysql-password',
      '/posts/change-mysql-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/change-redis-password': RouteRecordInfo<
      '/posts/change-redis-password',
      '/posts/change-redis-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/convert-int-to-string': RouteRecordInfo<
      '/posts/convert-int-to-string',
      '/posts/convert-int-to-string',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/convert-string-to-byte-slice': RouteRecordInfo<
      '/posts/convert-string-to-byte-slice',
      '/posts/convert-string-to-byte-slice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/convert-string-to-float': RouteRecordInfo<
      '/posts/convert-string-to-float',
      '/posts/convert-string-to-float',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/convert-string-to-rune-slice': RouteRecordInfo<
      '/posts/convert-string-to-rune-slice',
      '/posts/convert-string-to-rune-slice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/create-error': RouteRecordInfo<
      '/posts/create-error',
      '/posts/create-error',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/crypto-rand-int': RouteRecordInfo<
      '/posts/crypto-rand-int',
      '/posts/crypto-rand-int',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/defer-panic-and-recover': RouteRecordInfo<
      '/posts/defer-panic-and-recover',
      '/posts/defer-panic-and-recover',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/errors-explained': RouteRecordInfo<
      '/posts/errors-explained',
      '/posts/errors-explained',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/export-mysql-table-to-excel': RouteRecordInfo<
      '/posts/export-mysql-table-to-excel',
      '/posts/export-mysql-table-to-excel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/extra-mac-address-using-python': RouteRecordInfo<
      '/posts/extra-mac-address-using-python',
      '/posts/extra-mac-address-using-python',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/format-parse-string-time-date-example': RouteRecordInfo<
      '/posts/format-parse-string-time-date-example',
      '/posts/format-parse-string-time-date-example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/generate-number-random-range': RouteRecordInfo<
      '/posts/generate-number-random-range',
      '/posts/generate-number-random-range',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/generate-random-string': RouteRecordInfo<
      '/posts/generate-random-string',
      '/posts/generate-random-string',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/generate-uuid-guid': RouteRecordInfo<
      '/posts/generate-uuid-guid',
      '/posts/generate-uuid-guid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/github-pages-https': RouteRecordInfo<
      '/posts/github-pages-https',
      '/posts/github-pages-https',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/go-json': RouteRecordInfo<
      '/posts/go-json',
      '/posts/go-json',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/golang-excel': RouteRecordInfo<
      '/posts/golang-excel',
      '/posts/golang-excel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/golang-pointers': RouteRecordInfo<
      '/posts/golang-pointers',
      '/posts/golang-pointers',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/heartbeat': RouteRecordInfo<
      '/posts/heartbeat',
      '/posts/heartbeat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/history-and-history-file': RouteRecordInfo<
      '/posts/history-and-history-file',
      '/posts/history-and-history-file',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/history-usage': RouteRecordInfo<
      '/posts/history-usage',
      '/posts/history-usage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/how-to-sort-in-go': RouteRecordInfo<
      '/posts/how-to-sort-in-go',
      '/posts/how-to-sort-in-go',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/interface-to-string': RouteRecordInfo<
      '/posts/interface-to-string',
      '/posts/interface-to-string',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/iota': RouteRecordInfo<
      '/posts/iota',
      '/posts/iota',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/linux-netstat-command-examples': RouteRecordInfo<
      '/posts/linux-netstat-command-examples',
      '/posts/linux-netstat-command-examples',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/linux-ps-command-examples': RouteRecordInfo<
      '/posts/linux-ps-command-examples',
      '/posts/linux-ps-command-examples',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/multi-platform-compilation-of-golang': RouteRecordInfo<
      '/posts/multi-platform-compilation-of-golang',
      '/posts/multi-platform-compilation-of-golang',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-m2b-in-action': RouteRecordInfo<
      '/posts/mysql-m2b-in-action',
      '/posts/mysql-m2b-in-action',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pwa-install': RouteRecordInfo<
      '/posts/pwa-install',
      '/posts/pwa-install',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/recover-from-panic': RouteRecordInfo<
      '/posts/recover-from-panic',
      '/posts/recover-from-panic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/regex': RouteRecordInfo<
      '/posts/regex',
      '/posts/regex',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/rune': RouteRecordInfo<
      '/posts/rune',
      '/posts/rune',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/shuffle-slice-array': RouteRecordInfo<
      '/posts/shuffle-slice-array',
      '/posts/shuffle-slice-array',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/tar-zip-summary': RouteRecordInfo<
      '/posts/tar-zip-summary',
      '/posts/tar-zip-summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/type-assertion-switch': RouteRecordInfo<
      '/posts/type-assertion-switch',
      '/posts/type-assertion-switch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/using-v-model-with-objects': RouteRecordInfo<
      '/posts/using-v-model-with-objects',
      '/posts/using-v-model-with-objects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/view-mem-info-in-win10': RouteRecordInfo<
      '/posts/view-mem-info-in-win10',
      '/posts/view-mem-info-in-win10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/demos.md': {
      routes:
        | '/demos'
      views:
        | never
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/change-mysql-password.md': {
      routes:
        | '/posts/change-mysql-password'
      views:
        | never
    }
    'pages/posts/change-redis-password.md': {
      routes:
        | '/posts/change-redis-password'
      views:
        | never
    }
    'pages/posts/convert-int-to-string.md': {
      routes:
        | '/posts/convert-int-to-string'
      views:
        | never
    }
    'pages/posts/convert-string-to-byte-slice.md': {
      routes:
        | '/posts/convert-string-to-byte-slice'
      views:
        | never
    }
    'pages/posts/convert-string-to-float.md': {
      routes:
        | '/posts/convert-string-to-float'
      views:
        | never
    }
    'pages/posts/convert-string-to-rune-slice.md': {
      routes:
        | '/posts/convert-string-to-rune-slice'
      views:
        | never
    }
    'pages/posts/create-error.md': {
      routes:
        | '/posts/create-error'
      views:
        | never
    }
    'pages/posts/crypto-rand-int.md': {
      routes:
        | '/posts/crypto-rand-int'
      views:
        | never
    }
    'pages/posts/defer-panic-and-recover.md': {
      routes:
        | '/posts/defer-panic-and-recover'
      views:
        | never
    }
    'pages/posts/errors-explained.md': {
      routes:
        | '/posts/errors-explained'
      views:
        | never
    }
    'pages/posts/export-mysql-table-to-excel.md': {
      routes:
        | '/posts/export-mysql-table-to-excel'
      views:
        | never
    }
    'pages/posts/extra-mac-address-using-python.md': {
      routes:
        | '/posts/extra-mac-address-using-python'
      views:
        | never
    }
    'pages/posts/format-parse-string-time-date-example.md': {
      routes:
        | '/posts/format-parse-string-time-date-example'
      views:
        | never
    }
    'pages/posts/generate-number-random-range.md': {
      routes:
        | '/posts/generate-number-random-range'
      views:
        | never
    }
    'pages/posts/generate-random-string.md': {
      routes:
        | '/posts/generate-random-string'
      views:
        | never
    }
    'pages/posts/generate-uuid-guid.md': {
      routes:
        | '/posts/generate-uuid-guid'
      views:
        | never
    }
    'pages/posts/github-pages-https.md': {
      routes:
        | '/posts/github-pages-https'
      views:
        | never
    }
    'pages/posts/go-json.md': {
      routes:
        | '/posts/go-json'
      views:
        | never
    }
    'pages/posts/golang-excel.md': {
      routes:
        | '/posts/golang-excel'
      views:
        | never
    }
    'pages/posts/golang-pointers.md': {
      routes:
        | '/posts/golang-pointers'
      views:
        | never
    }
    'pages/posts/heartbeat.md': {
      routes:
        | '/posts/heartbeat'
      views:
        | never
    }
    'pages/posts/history-and-history-file.md': {
      routes:
        | '/posts/history-and-history-file'
      views:
        | never
    }
    'pages/posts/history-usage.md': {
      routes:
        | '/posts/history-usage'
      views:
        | never
    }
    'pages/posts/how-to-sort-in-go.md': {
      routes:
        | '/posts/how-to-sort-in-go'
      views:
        | never
    }
    'pages/posts/interface-to-string.md': {
      routes:
        | '/posts/interface-to-string'
      views:
        | never
    }
    'pages/posts/iota.md': {
      routes:
        | '/posts/iota'
      views:
        | never
    }
    'pages/posts/linux-netstat-command-examples.md': {
      routes:
        | '/posts/linux-netstat-command-examples'
      views:
        | never
    }
    'pages/posts/linux-ps-command-examples.md': {
      routes:
        | '/posts/linux-ps-command-examples'
      views:
        | never
    }
    'pages/posts/multi-platform-compilation-of-golang.md': {
      routes:
        | '/posts/multi-platform-compilation-of-golang'
      views:
        | never
    }
    'pages/posts/mysql-m2b-in-action.md': {
      routes:
        | '/posts/mysql-m2b-in-action'
      views:
        | never
    }
    'pages/posts/pwa-install.md': {
      routes:
        | '/posts/pwa-install'
      views:
        | never
    }
    'pages/posts/recover-from-panic.md': {
      routes:
        | '/posts/recover-from-panic'
      views:
        | never
    }
    'pages/posts/regex.md': {
      routes:
        | '/posts/regex'
      views:
        | never
    }
    'pages/posts/rune.md': {
      routes:
        | '/posts/rune'
      views:
        | never
    }
    'pages/posts/shuffle-slice-array.md': {
      routes:
        | '/posts/shuffle-slice-array'
      views:
        | never
    }
    'pages/posts/tar-zip-summary.md': {
      routes:
        | '/posts/tar-zip-summary'
      views:
        | never
    }
    'pages/posts/type-assertion-switch.md': {
      routes:
        | '/posts/type-assertion-switch'
      views:
        | never
    }
    'pages/posts/using-v-model-with-objects.md': {
      routes:
        | '/posts/using-v-model-with-objects'
      views:
        | never
    }
    'pages/posts/view-mem-info-in-win10.md': {
      routes:
        | '/posts/view-mem-info-in-win10'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
